# Generated by Django 3.1 on 2020-08-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification_last_read_time',
        ),
    ]
