# Generated by Django 3.1 on 2020-08-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200818_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
