[tool.black]
line-length = 88
exclude = 'migrations'

[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_django = 'django'
known_rest_framework = 'rest_framework'
known_first_party = 'notifications,posts,search,social,users'
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
profile = 'black'
sections = 'FUTURE,STDLIB,THIRDPARTY,REST_FRAMEWORK,DJANGO,FIRSTPARTY,LOCALFOLDER'
skip_gitignore = true
